emit:
  - "@azure-tools/typespec-autorest"

options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/"
    examples-directory: "${project-root}/examples"
    output-file: "openapi.json"